GET http://localhost:3000/CompanyCustomer
###
GET http://localhost:3000/PrivateCustomer/All
###
DELETE http://localhost:3000/PrivateCustomer/6
###
POST http://localhost:3000/PrivateCustomer/add
Content-Type: application/json 

{
    "id": 2,
    "adress": "1",
    "phoneNumber": "2",
    "email": "email@gmail.com",
    "fName": "tes",
    "lName": "testian", 
    "gender": "f"
}
###
POST http://localhost:3000/PrivateCustomer/update
Content-Type: application/json 

{
    "id": 3,
    "adress": "1",
    "phoneNumber": "2",
    "email": "email@gmail.com",
    "fName": "tes",
    "lName": "baldrian", 
    "gender": "f"
}
