export interface IUser {
  fname:string
  lname:string
  rank:string
  premissions:{
    admin:{
      read:boolean;
      write:boolean;
    }
    dashboard:{
      read:boolean;
      write:boolean;
    }
    crm:{
      read:boolean;
      write:boolean;
    }
    bills:{
      read:boolean;
      write:boolean;
    }
    products:{
      read:boolean;
      write:boolean;
    }
    settings:{
      read:boolean;
      write:boolean;
    }
  }
  image:string;
}
