# docker-compose.yml
version: '3.7'
services: 
  db: 
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: booklessdb
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "2345:5432"
  web:
    restart: always 
    build: .
    command: nodemon --legacy-watch src/server.ts
    depends_on: 
      - db
    volumes: 
      - ./src :/usr/app/src/
      - /app/node_modules
    ports: 
      - "3000:3000"