# docker-compose.yml
version: '3'
services: 
  web:
    build: .
    restart: always
    command: npm run dev
    volumes: 
      - .:/usr/app
      - /usr/app/node_modules
    ports: 
      - "3000:3000"
    depends_on: 
      - postgres

    environment: 
      DATABASE_URL: postgres://postgres@postgres/booklessdb
  
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: booklessdb
